name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  ORG_NAME: kaakaww
  IMAGE_NAME: dvwa-docker

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            $ORG_NAME/$IMAGE_NAME:latest
            $ORG_NAME/$IMAGE_NAME:{{ github.sha }}-arm64
            $ORG_NAME/$IMAGE_NAME:{{ github.sha }}-amd64
          push_tags: |
            $ORG_NAME/$IMAGE_NAME:latest
            $ORG_NAME/$IMAGE_NAME:{{ github.sha }}-arm64
            $ORG_NAME/$IMAGE_NAME:{{ github.sha }}-amd64
          manifest: true
          manifest_tags: |
            $ORG_NAME/$IMAGE_NAME:latest
            $ORG_NAME/$IMAGE_NAME:{{ github.sha }}
          platforms: |
            linux/amd64,linux/arm64