name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            kaakaww/dvwa-docker:latest-${{ matrix.architecture }}
            kaakaww/dvwa-docker:latest-${{ matrix.architecture }}
          platforms: |
            linux/amd64,linux/arm64